name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - cmake
  - pip:
    - face-recognition==1.3.0
    - fastapi==0.110.0
    - python-multipart==0.0.9
    - uvicorn==0.27.1
    - python-jose==3.3.0
    - passlib==1.7.4
    - python-dotenv==1.0.1
    - boto3==1.36.21
    - opencv-python==4.8.0.74 