schedule:
  daily:
    time: "02:00"  # UTC
    retention: 7    # days
  weekly:
    day: "Sunday"
    time: "03:00"  # UTC
    retention: 4    # weeks
  monthly:
    day: "1"
    time: "04:00"  # UTC
    retention: 6    # months

targets:
  database:
    type: "postgresql"
    compression: "gzip"
    destination: "s3://backup-bucket/database/"
  
  files:
    type: "filesystem"
    paths:
      - "/app/uploads"
      - "/app/config"
    compression: "tar.gz"
    destination: "s3://backup-bucket/files/"

  camera_recordings:
    type: "filesystem"
    paths:
      - "/app/recordings"
    compression: "tar.gz"
    destination: "s3://backup-bucket/recordings/" 