apiVersion: v1
kind: ConfigMap
metadata:
  name: disaster-recovery-config
data:
  recovery-regions:
    - name: primary
      region: us-east-1
      priority: 1
    - name: secondary
      region: us-west-2
      priority: 2
  
  failover-policy:
    automatic: true
    threshold-minutes: 5
    health-checks:
      - type: endpoint
        url: /api/health
        interval: 30s
        timeout: 5s
        failures-threshold: 3
      - type: database
        interval: 1m
        timeout: 10s
        failures-threshold: 3

  data-sync:
    interval: 5m
    includes:
      - database
      - file-storage
      - configuration 