apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-api
  namespace: face-recognition
spec:
  replicas: 3
  selector:
    matchLabels:
      app: face-recognition-api
  template:
    metadata:
      labels:
        app: face-recognition-api
    spec:
      containers:
      - name: face-recognition-api
        image: face-recognition-system:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: data
          mountPath: /app/data
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: MODEL_PATH
          value: "/app/models"
        - name: DATA_PATH
          value: "/app/data"
        - name: LOG_LEVEL
          value: "INFO"
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: face-recognition-api
  namespace: face-recognition
spec:
  selector:
    app: face-recognition-api
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: face-recognition-api
  namespace: face-recognition
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: face-recognition-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 