apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveillance-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveillance-system
  template:
    metadata:
      labels:
        app: surveillance-system
    spec:
      containers:
      - name: surveillance-system
        image: gcr.io/PROJECT_ID/surveillance-system:latest
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: PROJECT_ID
        - name: DATABASE_INSTANCE
          value: DATABASE_INSTANCE_NAME

---
apiVersion: cloud.google.com/v1
kind: CloudSQL
metadata:
  name: surveillance-db
spec:
  databaseVersion: POSTGRES_13
  settings:
    tier: db-f1-micro 